CREATE TABLE IF NOT EXISTS kv (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	ts TEXT NOT NULL,
	name TEXT NOT NULL,
	value TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_kv_name ON kv(name);
CREATE INDEX IF NOT EXISTS idx_kv_ts ON kv(ts);
